# Site settings
title: Gildásio Júnior
email: gildasio97+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/"
url: "http://gildasio.net"
twitter_username: jekyllrb
github_username:  gjuniioor

# Build settings
markdown: kramdown

# Global configuration
timezone: America/Bahia
encoding: UTF-8

# Build Command Options
lsi: TRUE

